trunk-version = "^0.21.4"

[build]
target = "web/index.html" # The index HTML file to drive the bundling process.

[serve]
#addresses = ["127.0.0.1"]  # The address to serve on.
port = 3000 # The port to serve on.
