trunk-version = "^0.21.4"

[build]
target = "web-app/index.html" # The index HTML file to drive the bundling process.
dist = "dist"

[serve]
#addresses = ["127.0.0.1"]  # The address to serve on.
port = 8888 # The port to serve on.

# [watch]
# ignore = ["**/*.css"]

# [[hooks]]
# stage = "post_build"
# command = "cp"
# command_arguments = ["-r", "./dist-styles/stylance", "./dist/styles"]
